SELECT C_CITY, sum(LO_ORDTOTALPRICE) AS total_sales
FROM
    lineorder
    JOIN part ON LO_PARTKEY = P_PARTKEY
    JOIN customer ON LO_CUSTKEY = C_CUSTKEY
WHERE P_CATEGORY = 'MFGR#32' AND P_BRAND = 'MFGR#3210'
GROUP BY C_CITY
ORDER BY total_sales DESC
LIMIT 10