SELECT C_CITY, sum(LO_ORDTOTALPRICE) AS total_sales
FROM
    lineorder
    JOIN customer ON LO_CUSTKEY = C_CUSTKEY
WHERE LO_PARTKEY IN (SELECT P_PARTKEY FROM part WHERE P_CATEGORY = 'MFGR#32' AND P_BRAND = 'MFGR#3210')
GROUP BY C_CITY
ORDER BY total_sales DESC
LIMIT 10
